// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPJOgl0CGGCeHY5WikxIZSy2eYdKHSZYw',
    appId: '1:107743385203:web:627f705061cb6702473c06',
    messagingSenderId: '107743385203',
    projectId: 'whispers-app-a5e82',
    authDomain: 'whispers-app-a5e82.firebaseapp.com',
    storageBucket: 'whispers-app-a5e82.firebasestorage.app',
    measurementId: 'G-P5P9JBN5HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrUHX3NSrYRxWft_q2wxNMnXFPs1o4UGc',
    appId: '1:107743385203:android:d10d3b3371256f9f473c06',
    messagingSenderId: '107743385203',
    projectId: 'whispers-app-a5e82',
    storageBucket: 'whispers-app-a5e82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfHhD0Kh0SrJVpqv10GibQ-i2LvNTI4UU',
    appId: '1:107743385203:ios:a9a10d021b4c8c35473c06',
    messagingSenderId: '107743385203',
    projectId: 'whispers-app-a5e82',
    storageBucket: 'whispers-app-a5e82.firebasestorage.app',
    iosBundleId: 'com.example.whispresApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfHhD0Kh0SrJVpqv10GibQ-i2LvNTI4UU',
    appId: '1:107743385203:ios:a9a10d021b4c8c35473c06',
    messagingSenderId: '107743385203',
    projectId: 'whispers-app-a5e82',
    storageBucket: 'whispers-app-a5e82.firebasestorage.app',
    iosBundleId: 'com.example.whispresApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPJOgl0CGGCeHY5WikxIZSy2eYdKHSZYw',
    appId: '1:107743385203:web:ef89b13cb71bdfcf473c06',
    messagingSenderId: '107743385203',
    projectId: 'whispers-app-a5e82',
    authDomain: 'whispers-app-a5e82.firebaseapp.com',
    storageBucket: 'whispers-app-a5e82.firebasestorage.app',
    measurementId: 'G-EQ97Q0CZ8W',
  );
}
